name: push workflow
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Execute container SQL
        run: docker-compose -f "./docker/docker-compose-MySQL.yml" up -d
      - name: Build native with Maven
        run: mvn -f "./contafin/pom.xml" test
      - name: Stop containers
        run: docker-compose -f "./docker/docker-compose-MySQL.yml" down